In [1]:
import pandas as pd
import numpy as np
import sys, os
from importlib import reload
import json
from pathlib import Path
from dataclasses import asdict

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..', 'src')))
from analysis import plots
import analysis.report
import training.gbm_model_trainer
from training.gbm_model_trainer import GBMModelTrainerConfig 

reload(analysis)
reload(analysis.plots)
reload(analysis.report)
reload(training.gbm_model_trainer)

## Load data

In [2]:
df = pd.read_csv("../data/bank-full.csv", delimiter=';')

In [3]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
# Convert 'y' to numeric for analysis
df["target"] = np.where(df["y"] == "no", 0, 1)

# Add weights to test weight functionality of plot_target_vs_predictors()
df["weights"] = np.abs(np.random.randn(len(df.index)))

# Add an arbitrary data split for testing functions
df["random"] = np.random.uniform(0, 1, len(df.index))
df["split"] = np.where(
    df["random"]  > 0.80, 
    "H", 
    np.where(
        df["random"]  > 0.50, 
        "V", 
        "T"
    )
)

In [5]:
df["split"].value_counts(dropna=False, normalize=True)

split
T    0.496008
V    0.302714
H    0.201278
Name: proportion, dtype: float64

In [6]:
df.groupby("split")["target"].mean()

split
H    0.117143
T    0.115942
V    0.118588
Name: target, dtype: float64

In [7]:
# Split data; define features and target
train = df.query("split == 'T'").drop(columns=["y", "split"])
test = df.query("split == 'V'").drop(columns=["y", "split"])
holdout = df.query("split == 'H'").drop(columns=["y", "split"])

## Use ModelTrainer class for hyperparameter tuning
- Test hyperparameter tuning

### Search over spaces

In [8]:
reload(training.gbm_model_trainer)
reload(analysis.report)
reload(analysis.plots)

In [9]:
from training.gbm_model_trainer import GBMModelTrainer
from xgboost import XGBClassifier

mt_xgboost = GBMModelTrainer(
    model_class=XGBClassifier,
    config_path="../examples/training_config_example_xgboost.yaml",
    train_df=train,
    valid_df=test,
    holdout_df=holdout
)

In [10]:
mt_xgboost.config

GBMModelTrainerConfig(actual_col='target', predicted_col='pred', output_dir='outputs', log_file='training.log', report_file='model_analysis.html', hyperparameters={'colsample_bytree': 0.5, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'objective': 'binary:logistic', 'random_state': 42, 'subsample': 0.5}, output_log=True, output_report=True, report_params={}, plots_to_add=[{'plot': 'plot_error_by_group_grid', 'title': 'Error by Analysis Variables', 'kwargs': {'group_cols': ['job', 'education', 'age']}}, {'plot': 'gain_curve_with_gini', 'title': 'Gain Curve / Lorenz Curve'}, {'plot': 'partial_gini_plot', 'title': 'Partial Gini (Top 15%)', 'kwargs': {'top_percent': 15}}, {'plot': 'lift_chart', 'title': 'Lift Chart'}, {'plot': 'crunched_residual_plot', 'title': 'Crunched Residuals'}, {'plot': 'plot_residual_fit', 'title': 'Std and Avg of Residuals', 'kwargs': {'residual_type': 'normalized'}}], tabulate_vars=['job', 'marital', 'education'], tuning=TuningConfig(search_space={'max_depth': Integer(low=3, high=10, prior='uniform', transform='identity'), 'learning_rate': Real(low=0.01, high=0.2, prior='log-uniform', transform='identity'), 'booster': Categorical(categories=('gbtree', 'dart'), prior=None)}, n_iter=20, scoring=make_scorer(normalized_gini, needs_proba=True), cv=3, output_tuning=True, n_jobs=1, tuning_file='tuning.csv'))

In [13]:
tuned_df = mt_xgboost.tune()
tuned_df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_booster,param_learning_rate,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,mean_train_score,std_train_score,rank_train_score
18,0.205039,0.000642,0.010564,0.000114,gbtree,0.021554,3,"{'booster': 'gbtree', 'learning_rate': 0.02155...",0.774316,0.565473,0.820809,0.720200,0.111042,1,0.845633,0.912030,0.858955,0.872206,0.028680,17
11,0.208317,0.002254,0.010540,0.000131,gbtree,0.019915,3,"{'booster': 'gbtree', 'learning_rate': 0.01991...",0.772192,0.567226,0.819668,0.719695,0.109540,2,0.843217,0.910261,0.857943,0.870474,0.028769,18
14,20.922568,0.050583,0.136355,0.000023,dart,0.018715,3,"{'booster': 'dart', 'learning_rate': 0.0187151...",0.767032,0.564382,0.820547,0.717320,0.110329,3,0.838811,0.908591,0.857125,0.868176,0.029539,19
7,19.989689,0.030499,0.138000,0.001119,dart,0.03044,3,"{'booster': 'dart', 'learning_rate': 0.0304399...",0.775291,0.546713,0.823658,0.715221,0.120778,4,0.855208,0.918161,0.866548,0.879972,0.027398,16
10,0.212065,0.013857,0.010807,0.000377,gbtree,0.01,3,"{'booster': 'gbtree', 'learning_rate': 0.01, '...",0.760743,0.554157,0.810587,0.708496,0.111015,5,0.824470,0.897828,0.844909,0.855736,0.030911,20

In [14]:
# Train using tuned hyperparameters
mt_xgboost.train()

✅ Analysis report generated at outputs/model_analysis.html

## Test with CAT Boost

In [15]:
from catboost import CatBoostClassifier
mt_catboost = GBMModelTrainer(
    model_class=CatBoostClassifier,
    config_path="../examples/training_config_example_catboost.yaml",
    train_df=train,
    valid_df=test,
    holdout_df=holdout
)

In [16]:
mt_catboost.config

GBMModelTrainerConfig(actual_col='target', predicted_col='pred', output_dir='outputs', log_file='training.log', report_file='model_analysis.html', hyperparameters={'n_estimators': 200}, output_log=True, output_report=True, report_params={}, plots_to_add=[{'plot': 'plot_error_by_group_grid', 'title': 'Error by Analysis Variables', 'kwargs': {'group_cols': ['job', 'education', 'age']}}, {'plot': 'gain_curve_with_gini', 'title': 'Gain Curve / Lorenz Curve'}, {'plot': 'partial_gini_plot', 'title': 'Partial Gini (Top 15%)', 'kwargs': {'top_percent': 15}}, {'plot': 'lift_chart', 'title': 'Lift Chart'}, {'plot': 'crunched_residual_plot', 'title': 'Crunched Residuals'}, {'plot': 'plot_residual_fit', 'title': 'Std and Avg of Residuals', 'kwargs': {'residual_type': 'normalized'}}], tabulate_vars=['job', 'marital', 'education'], tuning=TuningConfig(search_space={'depth': Integer(low=3, high=10, prior='uniform', transform='identity'), 'bagging_temperature': Real(low=0.01, high=0.95, prior='uniform', transform='identity'), 'leaf_estimation_iterations': Integer(low=1, high=10, prior='uniform', transform='identity'), 'random_strength': Real(low=1, high=20, prior='uniform', transform='identity'), 'l2_leaf_reg': Real(low=1, high=10, prior='uniform', transform='identity')}, n_iter=30, scoring=make_scorer(normalized_gini, needs_proba=True), cv=3, output_tuning=True, n_jobs=1, tuning_file='tuning.csv'))

In [19]:
mt_catboost.tune()

0:	learn: 0.6673295	total: 11.9ms	remaining: 2.37s
1:	learn: 0.6425595	total: 20.9ms	remaining: 2.07s
2:	learn: 0.6195463	total: 30.4ms	remaining: 2s
3:	learn: 0.6014448	total: 37.9ms	remaining: 1.86s
4:	learn: 0.5838326	total: 47.6ms	remaining: 1.85s
5:	learn: 0.5608441	total: 56ms	remaining: 1.81s
6:	learn: 0.5438229	total: 64.2ms	remaining: 1.77s
7:	learn: 0.5263321	total: 71.9ms	remaining: 1.73s
8:	learn: 0.5128891	total: 81.6ms	remaining: 1.73s
9:	learn: 0.4992749	total: 90.6ms	remaining: 1.72s
10:	learn: 0.4867353	total: 98.2ms	remaining: 1.69s
11:	learn: 0.4747716	total: 107ms	remaining: 1.67s
12:	learn: 0.4623341	total: 117ms	remaining: 1.68s
13:	learn: 0.4520853	total: 127ms	remaining: 1.69s
14:	learn: 0.4423056	total: 136ms	remaining: 1.68s
15:	learn: 0.4353082	total: 141ms	remaining: 1.62s
16:	learn: 0.4287936	total: 145ms	remaining: 1.56s
17:	learn: 0.4210965	total: 155ms	remaining: 1.57s
18:	learn: 0.4127370	total: 164ms	remaining: 1.56s
19:	learn: 0.4060943	total: 173ms	remaining: 1.55s
20:	learn: 0.4013084	total: 179ms	remaining: 1.53s
21:	learn: 0.3922366	total: 190ms	remaining: 1.53s
22:	learn: 0.3881927	total: 194ms	remaining: 1.49s
23:	learn: 0.3797506	total: 204ms	remaining: 1.5s
24:	learn: 0.3763380	total: 208ms	remaining: 1.46s
25:	learn: 0.3696620	total: 218ms	remaining: 1.46s
26:	learn: 0.3646577	total: 226ms	remaining: 1.45s
27:	learn: 0.3606013	total: 236ms	remaining: 1.45s
28:	learn: 0.3564092	total: 244ms	remaining: 1.44s
29:	learn: 0.3519045	total: 254ms	remaining: 1.44s
30:	learn: 0.3488381	total: 262ms	remaining: 1.43s
31:	learn: 0.3450547	total: 271ms	remaining: 1.42s
32:	learn: 0.3420750	total: 278ms	remaining: 1.41s
33:	learn: 0.3384173	total: 287ms	remaining: 1.4s
34:	learn: 0.3343468	total: 296ms	remaining: 1.4s
35:	learn: 0.3302963	total: 306ms	remaining: 1.4s
36:	learn: 0.3279390	total: 315ms	remaining: 1.39s
37:	learn: 0.3254380	total: 323ms	remaining: 1.38s
38:	learn: 0.3224412	total: 330ms	remaining: 1.36s
39:	learn: 0.3214590	total: 334ms	remaining: 1.34s
40:	learn: 0.3205399	total: 338ms	remaining: 1.31s
41:	learn: 0.3189508	total: 345ms	remaining: 1.3s
42:	learn: 0.3174940	total: 353ms	remaining: 1.29s
43:	learn: 0.3156234	total: 361ms	remaining: 1.28s
44:	learn: 0.3128026	total: 368ms	remaining: 1.27s
45:	learn: 0.3110332	total: 376ms	remaining: 1.26s
46:	learn: 0.3096782	total: 385ms	remaining: 1.25s
47:	learn: 0.3076053	total: 394ms	remaining: 1.25s
48:	learn: 0.3044990	total: 402ms	remaining: 1.24s
49:	learn: 0.3025861	total: 411ms	remaining: 1.23s
50:	learn: 0.3014457	total: 421ms	remaining: 1.23s
51:	learn: 0.2990351	total: 430ms	remaining: 1.22s
52:	learn: 0.2983683	total: 438ms	remaining: 1.21s
53:	learn: 0.2980655	total: 445ms	remaining: 1.2s
54:	learn: 0.2969602	total: 452ms	remaining: 1.19s
55:	learn: 0.2939398	total: 460ms	remaining: 1.18s
56:	learn: 0.2929857	total: 469ms	remaining: 1.18s
57:	learn: 0.2913833	total: 475ms	remaining: 1.16s
58:	learn: 0.2907464	total: 484ms	remaining: 1.16s
59:	learn: 0.2883193	total: 493ms	remaining: 1.15s
60:	learn: 0.2862621	total: 502ms	remaining: 1.14s
61:	learn: 0.2839647	total: 511ms	remaining: 1.14s
62:	learn: 0.2826108	total: 520ms	remaining: 1.13s
63:	learn: 0.2818434	total: 528ms	remaining: 1.12s
64:	learn: 0.2809650	total: 535ms	remaining: 1.11s
65:	learn: 0.2806689	total: 543ms	remaining: 1.1s
66:	learn: 0.2793670	total: 552ms	remaining: 1.09s
67:	learn: 0.2788608	total: 561ms	remaining: 1.09s
68:	learn: 0.2783137	total: 569ms	remaining: 1.08s
69:	learn: 0.2773682	total: 575ms	remaining: 1.07s
70:	learn: 0.2762448	total: 582ms	remaining: 1.06s
71:	learn: 0.2744179	total: 591ms	remaining: 1.05s
72:	learn: 0.2735356	total: 598ms	remaining: 1.04s
73:	learn: 0.2729750	total: 608ms	remaining: 1.03s
74:	learn: 0.2723674	total: 616ms	remaining: 1.03s
75:	learn: 0.2718944	total: 625ms	remaining: 1.02s
76:	learn: 0.2708925	total: 634ms	remaining: 1.01s
77:	learn: 0.2706582	total: 642ms	remaining: 1s
78:	learn: 0.2701126	total: 651ms	remaining: 997ms
79:	learn: 0.2699867	total: 660ms	remaining: 989ms
80:	learn: 0.2694815	total: 667ms	remaining: 980ms
81:	learn: 0.2688868	total: 675ms	remaining: 971ms
82:	learn: 0.2678393	total: 685ms	remaining: 966ms
83:	learn: 0.2669253	total: 694ms	remaining: 958ms
84:	learn: 0.2665368	total: 703ms	remaining: 952ms
85:	learn: 0.2663789	total: 707ms	remaining: 938ms
86:	learn: 0.2661281	total: 717ms	remaining: 931ms
87:	learn: 0.2656702	total: 726ms	remaining: 924ms
88:	learn: 0.2651339	total: 738ms	remaining: 920ms
89:	learn: 0.2641150	total: 747ms	remaining: 913ms
90:	learn: 0.2639555	total: 756ms	remaining: 905ms
91:	learn: 0.2633563	total: 765ms	remaining: 898ms
92:	learn: 0.2630834	total: 771ms	remaining: 887ms
93:	learn: 0.2630792	total: 775ms	remaining: 874ms
94:	learn: 0.2625594	total: 784ms	remaining: 866ms
95:	learn: 0.2617159	total: 793ms	remaining: 859ms
96:	learn: 0.2608625	total: 802ms	remaining: 851ms
97:	learn: 0.2608607	total: 805ms	remaining: 838ms
98:	learn: 0.2604089	total: 814ms	remaining: 831ms
99:	learn: 0.2598377	total: 823ms	remaining: 823ms
100:	learn: 0.2594848	total: 832ms	remaining: 816ms
101:	learn: 0.2588753	total: 842ms	remaining: 809ms
102:	learn: 0.2586912	total: 850ms	remaining: 801ms
103:	learn: 0.2586906	total: 854ms	remaining: 788ms
104:	learn: 0.2585793	total: 863ms	remaining: 781ms
105:	learn: 0.2585362	total: 870ms	remaining: 772ms
106:	learn: 0.2575484	total: 880ms	remaining: 765ms
107:	learn: 0.2571863	total: 888ms	remaining: 756ms
108:	learn: 0.2570266	total: 895ms	remaining: 747ms
109:	learn: 0.2566217	total: 905ms	remaining: 740ms
110:	learn: 0.2560889	total: 915ms	remaining: 734ms
111:	learn: 0.2558665	total: 922ms	remaining: 725ms
112:	learn: 0.2558665	total: 925ms	remaining: 712ms
113:	learn: 0.2553556	total: 935ms	remaining: 705ms
114:	learn: 0.2551279	total: 944ms	remaining: 698ms
115:	learn: 0.2548042	total: 955ms	remaining: 691ms
116:	learn: 0.2545812	total: 963ms	remaining: 683ms
117:	learn: 0.2544952	total: 973ms	remaining: 676ms
118:	learn: 0.2538353	total: 981ms	remaining: 668ms
119:	learn: 0.2535836	total: 990ms	remaining: 660ms
120:	learn: 0.2531464	total: 996ms	remaining: 650ms
121:	learn: 0.2527166	total: 1.01s	remaining: 643ms
122:	learn: 0.2521065	total: 1.01s	remaining: 635ms
123:	learn: 0.2518498	total: 1.02s	remaining: 627ms
124:	learn: 0.2516384	total: 1.03s	remaining: 620ms
125:	learn: 0.2514191	total: 1.04s	remaining: 612ms
126:	learn: 0.2510028	total: 1.05s	remaining: 605ms
127:	learn: 0.2500867	total: 1.06s	remaining: 597ms
128:	learn: 0.2498979	total: 1.07s	remaining: 589ms
129:	learn: 0.2496225	total: 1.08s	remaining: 580ms
130:	learn: 0.2494989	total: 1.09s	remaining: 572ms
131:	learn: 0.2494130	total: 1.09s	remaining: 564ms
132:	learn: 0.2493632	total: 1.1s	remaining: 556ms
133:	learn: 0.2493626	total: 1.11s	remaining: 545ms
134:	learn: 0.2493139	total: 1.11s	remaining: 536ms
135:	learn: 0.2492977	total: 1.12s	remaining: 528ms
136:	learn: 0.2492633	total: 1.13s	remaining: 520ms
137:	learn: 0.2491252	total: 1.14s	remaining: 511ms
138:	learn: 0.2490934	total: 1.14s	remaining: 502ms
139:	learn: 0.2490102	total: 1.15s	remaining: 494ms
140:	learn: 0.2482738	total: 1.16s	remaining: 486ms
141:	learn: 0.2480453	total: 1.17s	remaining: 478ms
142:	learn: 0.2478857	total: 1.18s	remaining: 470ms
143:	learn: 0.2477743	total: 1.19s	remaining: 462ms
144:	learn: 0.2474279	total: 1.2s	remaining: 454ms
145:	learn: 0.2472046	total: 1.2s	remaining: 446ms
146:	learn: 0.2471128	total: 1.22s	remaining: 438ms
147:	learn: 0.2470213	total: 1.22s	remaining: 430ms
148:	learn: 0.2469756	total: 1.23s	remaining: 421ms
149:	learn: 0.2468880	total: 1.24s	remaining: 413ms
150:	learn: 0.2468595	total: 1.25s	remaining: 405ms
151:	learn: 0.2465823	total: 1.26s	remaining: 397ms
152:	learn: 0.2464849	total: 1.26s	remaining: 389ms
153:	learn: 0.2460787	total: 1.27s	remaining: 381ms
154:	learn: 0.2459275	total: 1.28s	remaining: 373ms
155:	learn: 0.2459268	total: 1.29s	remaining: 364ms
156:	learn: 0.2455893	total: 1.3s	remaining: 356ms
157:	learn: 0.2455512	total: 1.31s	remaining: 348ms
158:	learn: 0.2452766	total: 1.32s	remaining: 340ms
159:	learn: 0.2451550	total: 1.32s	remaining: 331ms
160:	learn: 0.2451543	total: 1.33s	remaining: 322ms
161:	learn: 0.2451537	total: 1.33s	remaining: 313ms
162:	learn: 0.2448769	total: 1.34s	remaining: 305ms
163:	learn: 0.2446480	total: 1.35s	remaining: 296ms
164:	learn: 0.2444578	total: 1.35s	remaining: 288ms
165:	learn: 0.2443781	total: 1.37s	remaining: 280ms
166:	learn: 0.2443081	total: 1.38s	remaining: 272ms
167:	learn: 0.2442951	total: 1.38s	remaining: 263ms
168:	learn: 0.2442086	total: 1.39s	remaining: 255ms
169:	learn: 0.2442081	total: 1.4s	remaining: 246ms
170:	learn: 0.2439661	total: 1.4s	remaining: 238ms
171:	learn: 0.2438384	total: 1.41s	remaining: 230ms
172:	learn: 0.2436094	total: 1.42s	remaining: 222ms
173:	learn: 0.2431474	total: 1.43s	remaining: 214ms
174:	learn: 0.2431467	total: 1.43s	remaining: 205ms
175:	learn: 0.2431460	total: 1.44s	remaining: 196ms
176:	learn: 0.2429711	total: 1.45s	remaining: 188ms
177:	learn: 0.2427123	total: 1.46s	remaining: 180ms
178:	learn: 0.2422959	total: 1.46s	remaining: 172ms
179:	learn: 0.2422795	total: 1.47s	remaining: 164ms
180:	learn: 0.2420369	total: 1.49s	remaining: 156ms
181:	learn: 0.2419300	total: 1.49s	remaining: 148ms
182:	learn: 0.2417997	total: 1.5s	remaining: 140ms
183:	learn: 0.2416655	total: 1.51s	remaining: 131ms
184:	learn: 0.2415539	total: 1.52s	remaining: 123ms
185:	learn: 0.2415532	total: 1.52s	remaining: 115ms
186:	learn: 0.2415098	total: 1.53s	remaining: 106ms
187:	learn: 0.2414587	total: 1.54s	remaining: 98.1ms
188:	learn: 0.2414581	total: 1.54s	remaining: 89.6ms
189:	learn: 0.2413665	total: 1.55s	remaining: 81.5ms
190:	learn: 0.2413279	total: 1.56s	remaining: 73.4ms
191:	learn: 0.2413111	total: 1.57s	remaining: 65.3ms
192:	learn: 0.2412503	total: 1.57s	remaining: 57.1ms
193:	learn: 0.2412241	total: 1.58s	remaining: 48.9ms
194:	learn: 0.2411853	total: 1.58s	remaining: 40.7ms
195:	learn: 0.2410613	total: 1.59s	remaining: 32.6ms
196:	learn: 0.2408481	total: 1.6s	remaining: 24.4ms
197:	learn: 0.2405958	total: 1.61s	remaining: 16.3ms
198:	learn: 0.2404183	total: 1.62s	remaining: 8.13ms
199:	learn: 0.2402750	total: 1.63s	remaining: 0us
0:	learn: 0.6686245	total: 11.9ms	remaining: 2.36s
1:	learn: 0.6450259	total: 21.2ms	remaining: 2.1s
2:	learn: 0.6252497	total: 30.9ms	remaining: 2.03s
3:	learn: 0.6068423	total: 38.6ms	remaining: 1.89s
4:	learn: 0.5894281	total: 48.6ms	remaining: 1.89s
5:	learn: 0.5650799	total: 57.6ms	remaining: 1.86s
6:	learn: 0.5407707	total: 67.2ms	remaining: 1.85s
7:	learn: 0.5257783	total: 76.3ms	remaining: 1.83s
8:	learn: 0.5109488	total: 81.9ms	remaining: 1.74s
9:	learn: 0.4986352	total: 88.6ms	remaining: 1.68s
10:	learn: 0.4875086	total: 95.5ms	remaining: 1.64s
11:	learn: 0.4765098	total: 105ms	remaining: 1.65s
12:	learn: 0.4641837	total: 115ms	remaining: 1.66s
13:	learn: 0.4549949	total: 122ms	remaining: 1.62s
14:	learn: 0.4473797	total: 126ms	remaining: 1.55s
15:	learn: 0.4316164	total: 135ms	remaining: 1.55s
16:	learn: 0.4193244	total: 144ms	remaining: 1.55s
17:	learn: 0.4133196	total: 151ms	remaining: 1.53s
18:	learn: 0.4078973	total: 160ms	remaining: 1.53s
19:	learn: 0.3979625	total: 169ms	remaining: 1.52s
20:	learn: 0.3919624	total: 174ms	remaining: 1.48s
21:	learn: 0.3867419	total: 184ms	remaining: 1.49s
22:	learn: 0.3779376	total: 193ms	remaining: 1.49s
23:	learn: 0.3703475	total: 202ms	remaining: 1.48s
24:	learn: 0.3665983	total: 213ms	remaining: 1.49s
25:	learn: 0.3580707	total: 222ms	remaining: 1.49s
26:	learn: 0.3532143	total: 231ms	remaining: 1.48s
27:	learn: 0.3468726	total: 239ms	remaining: 1.47s
28:	learn: 0.3400621	total: 250ms	remaining: 1.47s
29:	learn: 0.3353742	total: 259ms	remaining: 1.47s
30:	learn: 0.3330191	total: 269ms	remaining: 1.47s
31:	learn: 0.3307199	total: 274ms	remaining: 1.44s
32:	learn: 0.3286751	total: 280ms	remaining: 1.42s
33:	learn: 0.3247956	total: 290ms	remaining: 1.42s
34:	learn: 0.3216355	total: 299ms	remaining: 1.41s
35:	learn: 0.3197711	total: 307ms	remaining: 1.4s
36:	learn: 0.3166878	total: 315ms	remaining: 1.39s
37:	learn: 0.3111999	total: 324ms	remaining: 1.38s
38:	learn: 0.3075460	total: 334ms	remaining: 1.38s
39:	learn: 0.3066772	total: 339ms	remaining: 1.35s
40:	learn: 0.3047587	total: 349ms	remaining: 1.35s
41:	learn: 0.3015903	total: 360ms	remaining: 1.35s
42:	learn: 0.2995014	total: 369ms	remaining: 1.35s
43:	learn: 0.2983447	total: 374ms	remaining: 1.32s
44:	learn: 0.2951666	total: 383ms	remaining: 1.32s
45:	learn: 0.2894635	total: 393ms	remaining: 1.31s
46:	learn: 0.2853616	total: 402ms	remaining: 1.31s
47:	learn: 0.2833758	total: 408ms	remaining: 1.29s
48:	learn: 0.2805864	total: 416ms	remaining: 1.28s
49:	learn: 0.2763766	total: 425ms	remaining: 1.27s
50:	learn: 0.2749720	total: 435ms	remaining: 1.27s
51:	learn: 0.2731173	total: 444ms	remaining: 1.26s
52:	learn: 0.2698055	total: 455ms	remaining: 1.26s
53:	learn: 0.2673982	total: 463ms	remaining: 1.25s
54:	learn: 0.2660798	total: 472ms	remaining: 1.24s
55:	learn: 0.2633803	total: 482ms	remaining: 1.24s
56:	learn: 0.2596944	total: 492ms	remaining: 1.23s
57:	learn: 0.2585949	total: 501ms	remaining: 1.23s
58:	learn: 0.2577657	total: 509ms	remaining: 1.22s
59:	learn: 0.2553209	total: 516ms	remaining: 1.2s
60:	learn: 0.2550573	total: 521ms	remaining: 1.19s
61:	learn: 0.2532946	total: 530ms	remaining: 1.18s
62:	learn: 0.2516359	total: 540ms	remaining: 1.17s
63:	learn: 0.2502085	total: 550ms	remaining: 1.17s
64:	learn: 0.2470837	total: 560ms	remaining: 1.16s
65:	learn: 0.2444578	total: 570ms	remaining: 1.16s
66:	learn: 0.2438800	total: 580ms	remaining: 1.15s
67:	learn: 0.2424309	total: 590ms	remaining: 1.15s
68:	learn: 0.2413873	total: 599ms	remaining: 1.14s
69:	learn: 0.2410234	total: 607ms	remaining: 1.13s
70:	learn: 0.2387930	total: 618ms	remaining: 1.12s
71:	learn: 0.2386689	total: 624ms	remaining: 1.11s
72:	learn: 0.2385511	total: 632ms	remaining: 1.1s
73:	learn: 0.2366938	total: 640ms	remaining: 1.09s
74:	learn: 0.2365944	total: 649ms	remaining: 1.08s
75:	learn: 0.2352434	total: 659ms	remaining: 1.07s
76:	learn: 0.2349805	total: 665ms	remaining: 1.06s
77:	learn: 0.2347718	total: 673ms	remaining: 1.05s
78:	learn: 0.2338013	total: 681ms	remaining: 1.04s
79:	learn: 0.2330777	total: 691ms	remaining: 1.04s
80:	learn: 0.2324165	total: 701ms	remaining: 1.03s
81:	learn: 0.2313416	total: 709ms	remaining: 1.02s
82:	learn: 0.2311154	total: 717ms	remaining: 1.01s
83:	learn: 0.2285194	total: 725ms	remaining: 1s
84:	learn: 0.2279502	total: 735ms	remaining: 994ms
85:	learn: 0.2276935	total: 743ms	remaining: 985ms
86:	learn: 0.2273211	total: 751ms	remaining: 976ms
87:	learn: 0.2260768	total: 760ms	remaining: 968ms
88:	learn: 0.2255235	total: 767ms	remaining: 957ms
89:	learn: 0.2251770	total: 773ms	remaining: 945ms
90:	learn: 0.2243779	total: 785ms	remaining: 940ms
91:	learn: 0.2241846	total: 795ms	remaining: 933ms
92:	learn: 0.2215082	total: 803ms	remaining: 924ms
93:	learn: 0.2212993	total: 813ms	remaining: 916ms
94:	learn: 0.2203799	total: 821ms	remaining: 907ms
95:	learn: 0.2203790	total: 824ms	remaining: 893ms
96:	learn: 0.2195460	total: 835ms	remaining: 887ms
97:	learn: 0.2192174	total: 844ms	remaining: 878ms
98:	learn: 0.2189906	total: 851ms	remaining: 868ms
99:	learn: 0.2187028	total: 857ms	remaining: 857ms
100:	learn: 0.2183333	total: 867ms	remaining: 850ms
101:	learn: 0.2177172	total: 877ms	remaining: 842ms
102:	learn: 0.2171246	total: 885ms	remaining: 834ms
103:	learn: 0.2161581	total: 895ms	remaining: 826ms
104:	learn: 0.2160729	total: 904ms	remaining: 818ms
105:	learn: 0.2157167	total: 914ms	remaining: 810ms
106:	learn: 0.2145867	total: 923ms	remaining: 802ms
107:	learn: 0.2141439	total: 933ms	remaining: 794ms
108:	learn: 0.2139832	total: 942ms	remaining: 786ms
109:	learn: 0.2132975	total: 952ms	remaining: 779ms
110:	learn: 0.2125042	total: 961ms	remaining: 771ms
111:	learn: 0.2116258	total: 970ms	remaining: 762ms
112:	learn: 0.2115767	total: 979ms	remaining: 754ms
113:	learn: 0.2109731	total: 989ms	remaining: 746ms
114:	learn: 0.2109726	total: 993ms	remaining: 734ms
115:	learn: 0.2102555	total: 1s	remaining: 726ms
116:	learn: 0.2098986	total: 1.01s	remaining: 717ms
117:	learn: 0.2098250	total: 1.02s	remaining: 707ms
118:	learn: 0.2092867	total: 1.02s	remaining: 698ms
119:	learn: 0.2092364	total: 1.03s	remaining: 689ms
120:	learn: 0.2069776	total: 1.04s	remaining: 682ms
121:	learn: 0.2069147	total: 1.05s	remaining: 673ms
122:	learn: 0.2066003	total: 1.06s	remaining: 664ms
123:	learn: 0.2056094	total: 1.07s	remaining: 656ms
124:	learn: 0.2055164	total: 1.08s	remaining: 647ms
125:	learn: 0.2052636	total: 1.09s	remaining: 639ms
126:	learn: 0.2052630	total: 1.09s	remaining: 627ms
127:	learn: 0.2051098	total: 1.1s	remaining: 619ms
128:	learn: 0.2048349	total: 1.1s	remaining: 609ms
129:	learn: 0.2045607	total: 1.12s	remaining: 601ms
130:	learn: 0.2044968	total: 1.12s	remaining: 591ms
131:	learn: 0.2043792	total: 1.13s	remaining: 582ms
132:	learn: 0.2042220	total: 1.14s	remaining: 573ms
133:	learn: 0.2041085	total: 1.15s	remaining: 564ms
134:	learn: 0.2040938	total: 1.15s	remaining: 554ms
135:	learn: 0.2038628	total: 1.16s	remaining: 546ms
136:	learn: 0.2034353	total: 1.17s	remaining: 537ms
137:	learn: 0.2034347	total: 1.17s	remaining: 527ms
138:	learn: 0.2032303	total: 1.18s	remaining: 518ms
139:	learn: 0.2029275	total: 1.19s	remaining: 510ms
140:	learn: 0.2028152	total: 1.2s	remaining: 502ms
141:	learn: 0.2021943	total: 1.21s	remaining: 493ms
142:	learn: 0.2001112	total: 1.22s	remaining: 485ms
143:	learn: 0.2000046	total: 1.22s	remaining: 476ms
144:	learn: 0.1995010	total: 1.23s	remaining: 467ms
145:	learn: 0.1991912	total: 1.24s	remaining: 459ms
146:	learn: 0.1990268	total: 1.25s	remaining: 450ms
147:	learn: 0.1986709	total: 1.26s	remaining: 442ms
148:	learn: 0.1986618	total: 1.27s	remaining: 433ms
149:	learn: 0.1984420	total: 1.27s	remaining: 424ms
150:	learn: 0.1976525	total: 1.28s	remaining: 416ms
151:	learn: 0.1971918	total: 1.29s	remaining: 408ms
152:	learn: 0.1970408	total: 1.3s	remaining: 399ms
153:	learn: 0.1969837	total: 1.31s	remaining: 391ms
154:	learn: 0.1967748	total: 1.32s	remaining: 382ms
155:	learn: 0.1958025	total: 1.33s	remaining: 374ms
156:	learn: 0.1956835	total: 1.34s	remaining: 366ms
157:	learn: 0.1956834	total: 1.34s	remaining: 356ms
158:	learn: 0.1954569	total: 1.35s	remaining: 348ms
159:	learn: 0.1954527	total: 1.35s	remaining: 338ms
160:	learn: 0.1952008	total: 1.36s	remaining: 330ms
161:	learn: 0.1951750	total: 1.37s	remaining: 321ms
162:	learn: 0.1947987	total: 1.38s	remaining: 313ms
163:	learn: 0.1947677	total: 1.39s	remaining: 304ms
164:	learn: 0.1945832	total: 1.39s	remaining: 296ms
165:	learn: 0.1943412	total: 1.4s	remaining: 288ms
166:	learn: 0.1941854	total: 1.41s	remaining: 279ms
167:	learn: 0.1936124	total: 1.42s	remaining: 271ms
168:	learn: 0.1931696	total: 1.43s	remaining: 263ms
169:	learn: 0.1929758	total: 1.44s	remaining: 255ms
170:	learn: 0.1927285	total: 1.45s	remaining: 246ms
171:	learn: 0.1925454	total: 1.46s	remaining: 238ms
172:	learn: 0.1925254	total: 1.47s	remaining: 230ms
173:	learn: 0.1923581	total: 1.48s	remaining: 222ms
174:	learn: 0.1923580	total: 1.49s	remaining: 212ms
175:	learn: 0.1923409	total: 1.5s	remaining: 204ms
176:	learn: 0.1911991	total: 1.5s	remaining: 196ms
177:	learn: 0.1911727	total: 1.51s	remaining: 187ms
178:	learn: 0.1909762	total: 1.51s	remaining: 178ms
179:	learn: 0.1909501	total: 1.52s	remaining: 169ms
180:	learn: 0.1909501	total: 1.53s	remaining: 160ms
181:	learn: 0.1908991	total: 1.53s	remaining: 152ms
182:	learn: 0.1897128	total: 1.54s	remaining: 143ms
183:	learn: 0.1895612	total: 1.55s	remaining: 135ms
184:	learn: 0.1895043	total: 1.56s	remaining: 127ms
185:	learn: 0.1894522	total: 1.57s	remaining: 119ms
186:	learn: 0.1894149	total: 1.58s	remaining: 110ms
187:	learn: 0.1887758	total: 1.59s	remaining: 102ms
188:	learn: 0.1883502	total: 1.6s	remaining: 93.2ms

/home/sagemaker-user/.conda/envs/NY_TIER_V140_SAGEMAKER/lib/python3.11/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "

0:	learn: 0.6748793	total: 5.76ms	remaining: 1.15s
1:	learn: 0.6585994	total: 11.2ms	remaining: 1.11s
2:	learn: 0.6423565	total: 15.4ms	remaining: 1.01s
3:	learn: 0.6278609	total: 18.8ms	remaining: 920ms
4:	learn: 0.6127578	total: 23.1ms	remaining: 899ms
5:	learn: 0.5998262	total: 28.3ms	remaining: 916ms
6:	learn: 0.5862093	total: 32.4ms	remaining: 893ms
7:	learn: 0.5746153	total: 36.5ms	remaining: 876ms
8:	learn: 0.5636636	total: 39.7ms	remaining: 842ms
9:	learn: 0.5532809	total: 42.2ms	remaining: 802ms
10:	learn: 0.5421070	total: 46.7ms	remaining: 803ms
11:	learn: 0.5324934	total: 50.4ms	remaining: 789ms
12:	learn: 0.5223314	total: 53.2ms	remaining: 765ms
13:	learn: 0.5127099	total: 56.3ms	remaining: 748ms
14:	learn: 0.5046508	total: 60.3ms	remaining: 744ms
15:	learn: 0.4970765	total: 63.8ms	remaining: 734ms
16:	learn: 0.4898709	total: 65.2ms	remaining: 702ms
17:	learn: 0.4830603	total: 69.1ms	remaining: 698ms
18:	learn: 0.4755619	total: 72.5ms	remaining: 691ms
19:	learn: 0.4693490	total: 76.4ms	remaining: 687ms
20:	learn: 0.4632442	total: 80.2ms	remaining: 684ms
21:	learn: 0.4574352	total: 84.1ms	remaining: 680ms
22:	learn: 0.4499524	total: 87.7ms	remaining: 675ms
23:	learn: 0.4437438	total: 92.6ms	remaining: 679ms
24:	learn: 0.4389210	total: 94.8ms	remaining: 663ms
25:	learn: 0.4329197	total: 101ms	remaining: 674ms
26:	learn: 0.4285514	total: 103ms	remaining: 661ms
27:	learn: 0.4233179	total: 107ms	remaining: 659ms
28:	learn: 0.4193600	total: 109ms	remaining: 642ms
29:	learn: 0.4156027	total: 113ms	remaining: 640ms
30:	learn: 0.4120191	total: 114ms	remaining: 624ms
31:	learn: 0.4081613	total: 118ms	remaining: 619ms
32:	learn: 0.4038570	total: 123ms	remaining: 621ms
33:	learn: 0.3996617	total: 127ms	remaining: 620ms
34:	learn: 0.3962812	total: 130ms	remaining: 611ms
35:	learn: 0.3934823	total: 133ms	remaining: 604ms
36:	learn: 0.3908283	total: 135ms	remaining: 597ms
37:	learn: 0.3864712	total: 140ms	remaining: 595ms
38:	learn: 0.3830457	total: 142ms	remaining: 588ms
39:	learn: 0.3807546	total: 145ms	remaining: 579ms
40:	learn: 0.3785103	total: 149ms	remaining: 579ms
41:	learn: 0.3753650	total: 152ms	remaining: 571ms
42:	learn: 0.3733022	total: 156ms	remaining: 569ms
43:	learn: 0.3705190	total: 160ms	remaining: 567ms
44:	learn: 0.3686187	total: 164ms	remaining: 565ms
45:	learn: 0.3657974	total: 169ms	remaining: 567ms
46:	learn: 0.3629083	total: 173ms	remaining: 563ms
47:	learn: 0.3610098	total: 177ms	remaining: 562ms
48:	learn: 0.3595416	total: 179ms	remaining: 551ms
49:	learn: 0.3572046	total: 182ms	remaining: 545ms
50:	learn: 0.3549942	total: 185ms	remaining: 540ms
51:	learn: 0.3525347	total: 187ms	remaining: 534ms
52:	learn: 0.3513426	total: 192ms	remaining: 533ms
53:	learn: 0.3493708	total: 196ms	remaining: 529ms
54:	learn: 0.3467144	total: 198ms	remaining: 522ms
55:	learn: 0.3456808	total: 200ms	remaining: 513ms
56:	learn: 0.3445794	total: 203ms	remaining: 508ms
57:	learn: 0.3425388	total: 207ms	remaining: 508ms
58:	learn: 0.3409025	total: 212ms	remaining: 506ms
59:	learn: 0.3380404	total: 216ms	remaining: 505ms
60:	learn: 0.3366342	total: 219ms	remaining: 499ms
61:	learn: 0.3343758	total: 222ms	remaining: 494ms
62:	learn: 0.3329531	total: 226ms	remaining: 492ms
63:	learn: 0.3322670	total: 228ms	remaining: 484ms
64:	learn: 0.3303603	total: 232ms	remaining: 482ms
65:	learn: 0.3289378	total: 234ms	remaining: 476ms
66:	learn: 0.3266856	total: 239ms	remaining: 474ms
67:	learn: 0.3261283	total: 240ms	remaining: 466ms
68:	learn: 0.3251029	total: 243ms	remaining: 461ms
69:	learn: 0.3234204	total: 247ms	remaining: 458ms
70:	learn: 0.3222836	total: 250ms	remaining: 454ms
71:	learn: 0.3212238	total: 252ms	remaining: 448ms
72:	learn: 0.3202662	total: 257ms	remaining: 446ms
73:	learn: 0.3193407	total: 261ms	remaining: 445ms
74:	learn: 0.3184659	total: 266ms	remaining: 444ms
75:	learn: 0.3163884	total: 272ms	remaining: 444ms
76:	learn: 0.3148178	total: 277ms	remaining: 442ms
77:	learn: 0.3144895	total: 278ms	remaining: 435ms
78:	learn: 0.3138250	total: 284ms	remaining: 434ms
79:	learn: 0.3135303	total: 285ms	remaining: 427ms
80:	learn: 0.3124203	total: 289ms	remaining: 424ms
81:	learn: 0.3117124	total: 293ms	remaining: 422ms
82:	learn: 0.3107113	total: 297ms	remaining: 418ms
83:	learn: 0.3104712	total: 301ms	remaining: 416ms
84:	learn: 0.3090489	total: 305ms	remaining: 413ms
85:	learn: 0.3085676	total: 309ms	remaining: 409ms
86:	learn: 0.3067686	total: 312ms	remaining: 406ms
87:	learn: 0.3061435	total: 317ms	remaining: 403ms
88:	learn: 0.3046497	total: 322ms	remaining: 401ms
89:	learn: 0.3037258	total: 327ms	remaining: 399ms
90:	learn: 0.3030574	total: 331ms	remaining: 397ms
91:	learn: 0.3017843	total: 336ms	remaining: 394ms
92:	learn: 0.3006440	total: 340ms	remaining: 392ms
93:	learn: 0.3001880	total: 344ms	remaining: 388ms
94:	learn: 0.2986896	total: 348ms	remaining: 385ms
95:	learn: 0.2982288	total: 351ms	remaining: 380ms
96:	learn: 0.2975103	total: 354ms	remaining: 375ms
97:	learn: 0.2971127	total: 356ms	remaining: 370ms
98:	learn: 0.2956863	total: 360ms	remaining: 367ms
99:	learn: 0.2949243	total: 365ms	remaining: 365ms
100:	learn: 0.2945929	total: 368ms	remaining: 361ms
101:	learn: 0.2936245	total: 372ms	remaining: 358ms
102:	learn: 0.2927233	total: 375ms	remaining: 353ms
103:	learn: 0.2917129	total: 380ms	remaining: 350ms
104:	learn: 0.2912742	total: 383ms	remaining: 346ms
105:	learn: 0.2898232	total: 389ms	remaining: 345ms
106:	learn: 0.2889162	total: 394ms	remaining: 343ms
107:	learn: 0.2882304	total: 399ms	remaining: 340ms
108:	learn: 0.2879758	total: 402ms	remaining: 335ms
109:	learn: 0.2866631	total: 406ms	remaining: 332ms
110:	learn: 0.2861470	total: 410ms	remaining: 328ms
111:	learn: 0.2852859	total: 414ms	remaining: 325ms
112:	learn: 0.2848884	total: 418ms	remaining: 322ms
113:	learn: 0.2846689	total: 423ms	remaining: 319ms
114:	learn: 0.2844608	total: 427ms	remaining: 316ms
115:	learn: 0.2836843	total: 431ms	remaining: 312ms
116:	learn: 0.2827350	total: 435ms	remaining: 309ms
117:	learn: 0.2823214	total: 440ms	remaining: 306ms
118:	learn: 0.2822881	total: 441ms	remaining: 300ms
119:	learn: 0.2820169	total: 444ms	remaining: 296ms
120:	learn: 0.2816482	total: 447ms	remaining: 292ms
121:	learn: 0.2808333	total: 452ms	remaining: 289ms
122:	learn: 0.2801747	total: 455ms	remaining: 285ms
123:	learn: 0.2801500	total: 457ms	remaining: 280ms
124:	learn: 0.2801131	total: 460ms	remaining: 276ms
125:	learn: 0.2798076	total: 464ms	remaining: 272ms
126:	learn: 0.2790933	total: 468ms	remaining: 269ms
127:	learn: 0.2783122	total: 472ms	remaining: 266ms
128:	learn: 0.2782937	total: 473ms	remaining: 261ms
129:	learn: 0.2778081	total: 476ms	remaining: 256ms
130:	learn: 0.2768026	total: 480ms	remaining: 253ms
131:	learn: 0.2764933	total: 483ms	remaining: 249ms
132:	learn: 0.2762652	total: 485ms	remaining: 244ms
133:	learn: 0.2756506	total: 490ms	remaining: 241ms
134:	learn: 0.2753081	total: 493ms	remaining: 237ms
135:	learn: 0.2751426	total: 496ms	remaining: 234ms
136:	learn: 0.2748865	total: 499ms	remaining: 229ms
137:	learn: 0.2748757	total: 500ms	remaining: 225ms
138:	learn: 0.2748566	total: 503ms	remaining: 221ms
139:	learn: 0.2747415	total: 507ms	remaining: 217ms
140:	learn: 0.2745483	total: 510ms	remaining: 214ms
141:	learn: 0.2736413	total: 514ms	remaining: 210ms
142:	learn: 0.2730806	total: 519ms	remaining: 207ms
143:	learn: 0.2730729	total: 521ms	remaining: 203ms
144:	learn: 0.2729607	total: 524ms	remaining: 199ms
145:	learn: 0.2725140	total: 527ms	remaining: 195ms
146:	learn: 0.2724210	total: 530ms	remaining: 191ms
147:	learn: 0.2721247	total: 533ms	remaining: 187ms
148:	learn: 0.2719112	total: 537ms	remaining: 184ms
149:	learn: 0.2714964	total: 541ms	remaining: 180ms
150:	learn: 0.2710067	total: 545ms	remaining: 177ms
151:	learn: 0.2709116	total: 550ms	remaining: 174ms
152:	learn: 0.2708042	total: 554ms	remaining: 170ms
153:	learn: 0.2706164	total: 558ms	remaining: 167ms
154:	learn: 0.2699036	total: 563ms	remaining: 164ms
155:	learn: 0.2695515	total: 567ms	remaining: 160ms
156:	learn: 0.2692895	total: 569ms	remaining: 156ms
157:	learn: 0.2689822	total: 572ms	remaining: 152ms
158:	learn: 0.2688360	total: 577ms	remaining: 149ms
159:	learn: 0.2684955	total: 580ms	remaining: 145ms
160:	learn: 0.2678256	total: 584ms	remaining: 141ms
161:	learn: 0.2677676	total: 588ms	remaining: 138ms
162:	learn: 0.2677189	total: 590ms	remaining: 134ms
163:	learn: 0.2673894	total: 593ms	remaining: 130ms
164:	learn: 0.2673008	total: 597ms	remaining: 127ms
165:	learn: 0.2669860	total: 599ms	remaining: 123ms
166:	learn: 0.2663631	total: 604ms	remaining: 119ms
167:	learn: 0.2656644	total: 609ms	remaining: 116ms
168:	learn: 0.2656197	total: 611ms	remaining: 112ms
169:	learn: 0.2653563	total: 613ms	remaining: 108ms
170:	learn: 0.2651169	total: 617ms	remaining: 105ms
171:	learn: 0.2650724	total: 620ms	remaining: 101ms
172:	learn: 0.2646183	total: 625ms	remaining: 97.5ms
173:	learn: 0.2646171	total: 626ms	remaining: 93.6ms
174:	learn: 0.2641417	total: 631ms	remaining: 90.1ms
175:	learn: 0.2638636	total: 635ms	remaining: 86.6ms
176:	learn: 0.2632777	total: 640ms	remaining: 83.1ms
177:	learn: 0.2631260	total: 644ms	remaining: 79.6ms
178:	learn: 0.2630397	total: 648ms	remaining: 76.1ms
179:	learn: 0.2629639	total: 652ms	remaining: 72.4ms
180:	learn: 0.2629631	total: 653ms	remaining: 68.6ms
181:	learn: 0.2623707	total: 657ms	remaining: 65ms
182:	learn: 0.2617349	total: 662ms	remaining: 61.5ms
183:	learn: 0.2616195	total: 664ms	remaining: 57.7ms
184:	learn: 0.2615749	total: 668ms	remaining: 54.2ms
185:	learn: 0.2614889	total: 672ms	remaining: 50.6ms
186:	learn: 0.2611967	total: 676ms	remaining: 47ms
187:	learn: 0.2610816	total: 679ms	remaining: 43.3ms
188:	learn: 0.2605525	total: 683ms	remaining: 39.7ms
189:	learn: 0.2604734	total: 687ms	remaining: 36.2ms
190:	learn: 0.2603678	total: 691ms	remaining: 32.6ms
191:	learn: 0.2602676	total: 696ms	remaining: 29ms
192:	learn: 0.2602668	total: 701ms	remaining: 25.4ms
193:	learn: 0.2597680	total: 705ms	remaining: 21.8ms
194:	learn: 0.2596563	total: 710ms	remaining: 18.2ms
195:	learn: 0.2592129	total: 714ms	remaining: 14.6ms
196:	learn: 0.2591257	total: 718ms	remaining: 10.9ms
197:	learn: 0.2591114	total: 723ms	remaining: 7.3ms
198:	learn: 0.2590467	total: 726ms	remaining: 3.65ms
199:	learn: 0.2587954	total: 729ms	remaining: 0us
0:	learn: 0.6753973	total: 5.17ms	remaining: 1.03s
1:	learn: 0.6591105	total: 10.3ms	remaining: 1.02s
2:	learn: 0.6437668	total: 13.2ms	remaining: 870ms
3:	learn: 0.6285783	total: 18.7ms	remaining: 915ms
4:	learn: 0.6148846	total: 20.6ms	remaining: 805ms
5:	learn: 0.6019651	total: 23.6ms	remaining: 762ms
6:	learn: 0.5898006	total: 27.8ms	remaining: 767ms
7:	learn: 0.5782805	total: 32ms	remaining: 768ms
8:	learn: 0.5664367	total: 36.1ms	remaining: 767ms
9:	learn: 0.5560576	total: 39.8ms	remaining: 756ms
10:	learn: 0.5454006	total: 43.8ms	remaining: 753ms
11:	learn: 0.5360306	total: 46.2ms	remaining: 724ms
12:	learn: 0.5271744	total: 48ms	remaining: 690ms
13:	learn: 0.5179875	total: 53ms	remaining: 704ms
14:	learn: 0.5096151	total: 55.9ms	remaining: 689ms
15:	learn: 0.5011865	total: 59.3ms	remaining: 682ms
16:	learn: 0.4932705	total: 61.8ms	remaining: 665ms
17:	learn: 0.4863222	total: 64.2ms	remaining: 649ms
18:	learn: 0.4798217	total: 66.4ms	remaining: 632ms
19:	learn: 0.4736718	total: 70.6ms	remaining: 635ms
20:	learn: 0.4676801	total: 73.5ms	remaining: 627ms
21:	learn: 0.4611810	total: 76.9ms	remaining: 622ms
22:	learn: 0.4542343	total: 79.7ms	remaining: 613ms
23:	learn: 0.4487802	total: 82.8ms	remaining: 607ms
24:	learn: 0.4439662	total: 85.4ms	remaining: 598ms
25:	learn: 0.4387463	total: 89.8ms	remaining: 601ms
26:	learn: 0.4329327	total: 93.5ms	remaining: 599ms
27:	learn: 0.4286787	total: 96.4ms	remaining: 592ms
28:	learn: 0.4234404	total: 99.5ms	remaining: 587ms
29:	learn: 0.4181371	total: 103ms	remaining: 583ms
30:	learn: 0.4145637	total: 106ms	remaining: 576ms
31:	learn: 0.4111601	total: 107ms	remaining: 563ms
32:	learn: 0.4076473	total: 110ms	remaining: 557ms
33:	learn: 0.4034907	total: 114ms	remaining: 555ms
34:	learn: 0.3983151	total: 118ms	remaining: 556ms
35:	learn: 0.3944120	total: 121ms	remaining: 552ms
36:	learn: 0.3908351	total: 123ms	remaining: 543ms
37:	learn: 0.3867940	total: 126ms	remaining: 538ms
38:	learn: 0.3838057	total: 128ms	remaining: 529ms
39:	learn: 0.3808566	total: 134ms	remaining: 535ms
40:	learn: 0.3786776	total: 135ms	remaining: 524ms
41:	learn: 0.3760681	total: 138ms	remaining: 521ms
42:	learn: 0.3713121	total: 142ms	remaining: 518ms
43:	learn: 0.3669959	total: 146ms	remaining: 518ms
44:	learn: 0.3647189	total: 151ms	remaining: 519ms
45:	learn: 0.3630239	total: 154ms	remaining: 517ms
46:	learn: 0.3614086	total: 156ms	remaining: 508ms
47:	learn: 0.3573839	total: 162ms	remaining: 512ms
48:	learn: 0.3541078	total: 165ms	remaining: 509ms
49:	learn: 0.3508540	total: 169ms	remaining: 507ms
50:	learn: 0.3489503	total: 172ms	remaining: 502ms
51:	learn: 0.3476026	total: 175ms	remaining: 497ms
52:	learn: 0.3464076	total: 176ms	remaining: 488ms
53:	learn: 0.3441518	total: 180ms	remaining: 487ms
54:	learn: 0.3410376	total: 183ms	remaining: 483ms
55:	learn: 0.3389356	total: 187ms	remaining: 482ms
56:	learn: 0.3356648	total: 192ms	remaining: 481ms
57:	learn: 0.3329182	total: 196ms	remaining: 481ms
58:	learn: 0.3314436	total: 200ms	remaining: 477ms
59:	learn: 0.3295765	total: 204ms	remaining: 476ms
60:	learn: 0.3266773	total: 208ms	remaining: 474ms
61:	learn: 0.3254868	total: 211ms	remaining: 471ms
62:	learn: 0.3231191	total: 215ms	remaining: 467ms
63:	learn: 0.3223725	total: 221ms	remaining: 469ms
64:	learn: 0.3208205	total: 225ms	remaining: 468ms
65:	learn: 0.3177610	total: 230ms	remaining: 467ms
66:	learn: 0.3162605	total: 235ms	remaining: 466ms
67:	learn: 0.3151543	total: 239ms	remaining: 465ms
68:	learn: 0.3124836	total: 243ms	remaining: 461ms
69:	learn: 0.3097436	total: 248ms	remaining: 460ms
70:	learn: 0.3070602	total: 252ms	remaining: 459ms
71:	learn: 0.3066117	total: 254ms	remaining: 451ms
72:	learn: 0.3043970	total: 258ms	remaining: 449ms
73:	learn: 0.3022155	total: 262ms	remaining: 446ms
74:	learn: 0.3018333	total: 263ms	remaining: 439ms
75:	learn: 0.3002282	total: 267ms	remaining: 435ms
76:	learn: 0.2982668	total: 270ms	remaining: 432ms
77:	learn: 0.2964109	total: 275ms	remaining: 430ms
78:	learn: 0.2957362	total: 278ms	remaining: 426ms
79:	learn: 0.2946682	total: 282ms	remaining: 423ms
80:	learn: 0.2924587	total: 287ms	remaining: 422ms
81:	learn: 0.2901453	total: 291ms	remaining: 419ms
82:	learn: 0.2894426	total: 296ms	remaining: 417ms
83:	learn: 0.2871727	total: 300ms	remaining: 414ms
84:	learn: 0.2853174	total: 304ms	remaining: 411ms
85:	learn: 0.2844220	total: 308ms	remaining: 408ms
86:	learn: 0.2837388	total: 311ms	remaining: 404ms
87:	learn: 0.2819646	total: 315ms	remaining: 400ms
88:	learn: 0.2812213	total: 317ms	remaining: 396ms
89:	learn: 0.2810523	total: 319ms	remaining: 389ms
90:	learn: 0.2806060	total: 322ms	remaining: 385ms
91:	learn: 0.2789421	total: 326ms	remaining: 383ms
92:	learn: 0.2781627	total: 330ms	remaining: 380ms
93:	learn: 0.2776508	total: 334ms	remaining: 377ms
94:	learn: 0.2774625	total: 336ms	remaining: 372ms
95:	learn: 0.2756511	total: 341ms	remaining: 369ms
96:	learn: 0.2749834	total: 345ms	remaining: 366ms
97:	learn: 0.2737589	total: 349ms	remaining: 363ms
98:	learn: 0.2726207	total: 351ms	remaining: 358ms
99:	learn: 0.2721730	total: 355ms	remaining: 355ms
100:	learn: 0.2710195	total: 359ms	remaining: 352ms
101:	learn: 0.2704131	total: 364ms	remaining: 350ms
102:	learn: 0.2693617	total: 369ms	remaining: 348ms
103:	learn: 0.2682798	total: 373ms	remaining: 344ms
104:	learn: 0.2675323	total: 375ms	remaining: 339ms
105:	learn: 0.2671059	total: 378ms	remaining: 336ms
106:	learn: 0.2665097	total: 382ms	remaining: 332ms
107:	learn: 0.2653989	total: 387ms	remaining: 330ms
108:	learn: 0.2645713	total: 391ms	remaining: 327ms
109:	learn: 0.2633811	total: 395ms	remaining: 324ms
110:	learn: 0.2629152	total: 398ms	remaining: 319ms
111:	learn: 0.2609426	total: 403ms	remaining: 317ms
112:	learn: 0.2602575	total: 407ms	remaining: 314ms
113:	learn: 0.2598500	total: 411ms	remaining: 310ms
114:	learn: 0.2595010	total: 415ms	remaining: 306ms
115:	learn: 0.2585533	total: 420ms	remaining: 304ms
116:	learn: 0.2574220	total: 423ms	remaining: 300ms
117:	learn: 0.2571509	total: 427ms	remaining: 297ms
118:	learn: 0.2566556	total: 432ms	remaining: 294ms
119:	learn: 0.2557563	total: 436ms	remaining: 290ms
120:	learn: 0.2553887	total: 439ms	remaining: 287ms
121:	learn: 0.2540570	total: 442ms	remaining: 283ms
122:	learn: 0.2537119	total: 446ms	remaining: 279ms
123:	learn: 0.2532708	total: 449ms	remaining: 275ms
124:	learn: 0.2516377	total: 453ms	remaining: 272ms
125:	learn: 0.2506636	total: 458ms	remaining: 269ms
126:	learn: 0.2497294	total: 461ms	remaining: 265ms
127:	learn: 0.2493426	total: 465ms	remaining: 262ms
128:	learn: 0.2491529	total: 468ms	remaining: 258ms
129:	learn: 0.2483968	total: 472ms	remaining: 254ms
130:	learn: 0.2480137	total: 476ms	remaining: 251ms
131:	learn: 0.2472558	total: 479ms	remaining: 247ms
132:	learn: 0.2472417	total: 480ms	remaining: 242ms
133:	learn: 0.2470825	total: 484ms	remaining: 238ms
134:	learn: 0.2465066	total: 487ms	remaining: 235ms
135:	learn: 0.2453623	total: 491ms	remaining: 231ms
136:	learn: 0.2451574	total: 494ms	remaining: 227ms
137:	learn: 0.2449708	total: 498ms	remaining: 224ms
138:	learn: 0.2447327	total: 501ms	remaining: 220ms
139:	learn: 0.2444020	total: 505ms	remaining: 216ms
140:	learn: 0.2441103	total: 509ms	remaining: 213ms
141:	learn: 0.2438665	total: 512ms	remaining: 209ms
142:	learn: 0.2428944	total: 516ms	remaining: 206ms
143:	learn: 0.2428655	total: 518ms	remaining: 201ms
144:	learn: 0.2424758	total: 521ms	remaining: 198ms
145:	learn: 0.2415271	total: 525ms	remaining: 194ms
146:	learn: 0.2408745	total: 528ms	remaining: 190ms
147:	learn: 0.2399991	total: 536ms	remaining: 188ms
148:	learn: 0.2396411	total: 540ms	remaining: 185ms
149:	learn: 0.2387801	total: 545ms	remaining: 182ms
150:	learn: 0.2381362	total: 549ms	remaining: 178ms
151:	learn: 0.2380463	total: 553ms	remaining: 175ms
152:	learn: 0.2373710	total: 558ms	remaining: 172ms
153:	learn: 0.2370978	total: 561ms	remaining: 168ms
154:	learn: 0.2363826	total: 565ms	remaining: 164ms
155:	learn: 0.2361451	total: 570ms	remaining: 161ms
156:	learn: 0.2360717	total: 575ms	remaining: 157ms
157:	learn: 0.2355062	total: 579ms	remaining: 154ms
158:	learn: 0.2349137	total: 585ms	remaining: 151ms
159:	learn: 0.2346585	total: 588ms	remaining: 147ms
160:	learn: 0.2346558	total: 590ms	remaining: 143ms
161:	learn: 0.2340144	total: 595ms	remaining: 140ms
162:	learn: 0.2339066	total: 598ms	remaining: 136ms
163:	learn: 0.2337879	total: 601ms	remaining: 132ms
164:	learn: 0.2332832	total: 604ms	remaining: 128ms
165:	learn: 0.2328151	total: 610ms	remaining: 125ms
166:	learn: 0.2327252	total: 614ms	remaining: 121ms
167:	learn: 0.2321216	total: 619ms	remaining: 118ms
168:	learn: 0.2319032	total: 623ms	remaining: 114ms
169:	learn: 0.2313854	total: 629ms	remaining: 111ms
170:	learn: 0.2311551	total: 633ms	remaining: 107ms
171:	learn: 0.2311092	total: 636ms	remaining: 104ms
172:	learn: 0.2311080	total: 638ms	remaining: 99.5ms
173:	learn: 0.2305932	total: 641ms	remaining: 95.8ms
174:	learn: 0.2303826	total: 645ms	remaining: 92.2ms
175:	learn: 0.2302480	total: 649ms	remaining: 88.6ms
176:	learn: 0.2297219	total: 654ms	remaining: 85ms
177:	learn: 0.2290707	total: 658ms	remaining: 81.4ms
178:	learn: 0.2290698	total: 660ms	remaining: 77.4ms
179:	learn: 0.2288986	total: 664ms	remaining: 73.8ms
180:	learn: 0.2287732	total: 668ms	remaining: 70.2ms
181:	learn: 0.2287722	total: 672ms	remaining: 66.4ms
182:	learn: 0.2287007	total: 675ms	remaining: 62.7ms
183:	learn: 0.2283546	total: 679ms	remaining: 59.1ms
184:	learn: 0.2282763	total: 682ms	remaining: 55.3ms
185:	learn: 0.2275250	total: 686ms	remaining: 51.6ms
186:	learn: 0.2270989	total: 689ms	remaining: 47.9ms

/home/sagemaker-user/.conda/envs/NY_TIER_V140_SAGEMAKER/lib/python3.11/site-packages/skopt/optimizer/optimizer.py:449: UserWarning: The objective has been evaluated at this point before.
  warnings.warn("The objective has been evaluated "

0:	learn: 0.6748793	total: 5.47ms	remaining: 1.09s
1:	learn: 0.6585994	total: 10.6ms	remaining: 1.05s
2:	learn: 0.6423565	total: 14.7ms	remaining: 967ms
3:	learn: 0.6278609	total: 18.4ms	remaining: 900ms
4:	learn: 0.6127578	total: 22.4ms	remaining: 875ms
5:	learn: 0.5998262	total: 26.9ms	remaining: 871ms
6:	learn: 0.5862093	total: 31.4ms	remaining: 864ms
7:	learn: 0.5746153	total: 35.5ms	remaining: 852ms
8:	learn: 0.5636636	total: 38.5ms	remaining: 817ms
9:	learn: 0.5532809	total: 41ms	remaining: 779ms
10:	learn: 0.5421070	total: 45.8ms	remaining: 787ms
11:	learn: 0.5324934	total: 49.4ms	remaining: 774ms
12:	learn: 0.5223314	total: 52.2ms	remaining: 750ms
13:	learn: 0.5127099	total: 55.4ms	remaining: 736ms
14:	learn: 0.5046508	total: 59.4ms	remaining: 733ms
15:	learn: 0.4970765	total: 62.5ms	remaining: 719ms
16:	learn: 0.4898709	total: 63.9ms	remaining: 687ms
17:	learn: 0.4830603	total: 67.8ms	remaining: 685ms
18:	learn: 0.4755619	total: 71.2ms	remaining: 678ms
19:	learn: 0.4693490	total: 75.1ms	remaining: 676ms
20:	learn: 0.4632442	total: 79ms	remaining: 673ms
21:	learn: 0.4574352	total: 82.9ms	remaining: 671ms
22:	learn: 0.4499524	total: 86.6ms	remaining: 666ms
23:	learn: 0.4437438	total: 91.2ms	remaining: 669ms
24:	learn: 0.4389210	total: 92.7ms	remaining: 649ms
25:	learn: 0.4329197	total: 98.3ms	remaining: 658ms
26:	learn: 0.4285514	total: 99.7ms	remaining: 639ms
27:	learn: 0.4233179	total: 104ms	remaining: 638ms
28:	learn: 0.4193600	total: 105ms	remaining: 621ms
29:	learn: 0.4156027	total: 109ms	remaining: 617ms
30:	learn: 0.4120191	total: 111ms	remaining: 603ms
31:	learn: 0.4081613	total: 114ms	remaining: 600ms
32:	learn: 0.4038570	total: 119ms	remaining: 601ms
33:	learn: 0.3996617	total: 123ms	remaining: 600ms
34:	learn: 0.3962812	total: 125ms	remaining: 591ms
35:	learn: 0.3934823	total: 128ms	remaining: 584ms
36:	learn: 0.3908283	total: 131ms	remaining: 577ms
37:	learn: 0.3864712	total: 135ms	remaining: 575ms
38:	learn: 0.3830457	total: 138ms	remaining: 569ms
39:	learn: 0.3807546	total: 140ms	remaining: 561ms
40:	learn: 0.3785103	total: 145ms	remaining: 563ms
41:	learn: 0.3753650	total: 148ms	remaining: 556ms
42:	learn: 0.3733022	total: 152ms	remaining: 555ms
43:	learn: 0.3705190	total: 156ms	remaining: 553ms
44:	learn: 0.3686187	total: 159ms	remaining: 549ms
45:	learn: 0.3657974	total: 165ms	remaining: 551ms
46:	learn: 0.3629083	total: 168ms	remaining: 547ms
47:	learn: 0.3610098	total: 172ms	remaining: 544ms
48:	learn: 0.3595416	total: 173ms	remaining: 534ms
49:	learn: 0.3572046	total: 176ms	remaining: 529ms
50:	learn: 0.3549942	total: 179ms	remaining: 523ms
51:	learn: 0.3525347	total: 181ms	remaining: 516ms
52:	learn: 0.3513426	total: 186ms	remaining: 516ms
53:	learn: 0.3493708	total: 190ms	remaining: 513ms
54:	learn: 0.3467144	total: 192ms	remaining: 506ms
55:	learn: 0.3456808	total: 194ms	remaining: 498ms
56:	learn: 0.3445794	total: 196ms	remaining: 493ms
57:	learn: 0.3425388	total: 201ms	remaining: 492ms
58:	learn: 0.3409025	total: 206ms	remaining: 491ms
59:	learn: 0.3380404	total: 210ms	remaining: 490ms
60:	learn: 0.3366342	total: 212ms	remaining: 484ms
61:	learn: 0.3343758	total: 215ms	remaining: 479ms
62:	learn: 0.3329531	total: 220ms	remaining: 478ms
63:	learn: 0.3322670	total: 221ms	remaining: 470ms
64:	learn: 0.3303603	total: 226ms	remaining: 468ms
65:	learn: 0.3289378	total: 228ms	remaining: 463ms
66:	learn: 0.3266856	total: 232ms	remaining: 461ms
67:	learn: 0.3261283	total: 234ms	remaining: 453ms
68:	learn: 0.3251029	total: 237ms	remaining: 450ms
69:	learn: 0.3234204	total: 241ms	remaining: 447ms
70:	learn: 0.3222836	total: 244ms	remaining: 443ms
71:	learn: 0.3212238	total: 246ms	remaining: 438ms
72:	learn: 0.3202662	total: 251ms	remaining: 436ms
73:	learn: 0.3193407	total: 255ms	remaining: 434ms
74:	learn: 0.3184659	total: 260ms	remaining: 434ms
75:	learn: 0.3163884	total: 266ms	remaining: 433ms
76:	learn: 0.3148178	total: 270ms	remaining: 431ms
77:	learn: 0.3144895	total: 271ms	remaining: 425ms
78:	learn: 0.3138250	total: 276ms	remaining: 423ms
79:	learn: 0.3135303	total: 278ms	remaining: 417ms
80:	learn: 0.3124203	total: 282ms	remaining: 415ms
81:	learn: 0.3117124	total: 286ms	remaining: 412ms
82:	learn: 0.3107113	total: 290ms	remaining: 408ms
83:	learn: 0.3104712	total: 294ms	remaining: 406ms
84:	learn: 0.3090489	total: 298ms	remaining: 403ms
85:	learn: 0.3085676	total: 301ms	remaining: 399ms
86:	learn: 0.3067686	total: 304ms	remaining: 395ms
87:	learn: 0.3061435	total: 309ms	remaining: 393ms
88:	learn: 0.3046497	total: 313ms	remaining: 391ms
89:	learn: 0.3037258	total: 318ms	remaining: 388ms
90:	learn: 0.3030574	total: 322ms	remaining: 386ms
91:	learn: 0.3017843	total: 327ms	remaining: 383ms
92:	learn: 0.3006440	total: 331ms	remaining: 381ms
93:	learn: 0.3001880	total: 335ms	remaining: 378ms
94:	learn: 0.2986896	total: 339ms	remaining: 374ms
95:	learn: 0.2982288	total: 342ms	remaining: 370ms
96:	learn: 0.2975103	total: 344ms	remaining: 365ms
97:	learn: 0.2971127	total: 347ms	remaining: 361ms
98:	learn: 0.2956863	total: 351ms	remaining: 358ms
99:	learn: 0.2949243	total: 355ms	remaining: 355ms
100:	learn: 0.2945929	total: 358ms	remaining: 351ms
101:	learn: 0.2936245	total: 362ms	remaining: 348ms
102:	learn: 0.2927233	total: 364ms	remaining: 343ms
103:	learn: 0.2917129	total: 369ms	remaining: 341ms
104:	learn: 0.2912742	total: 371ms	remaining: 336ms
105:	learn: 0.2898232	total: 376ms	remaining: 333ms
106:	learn: 0.2889162	total: 380ms	remaining: 330ms
107:	learn: 0.2882304	total: 385ms	remaining: 328ms
108:	learn: 0.2879758	total: 388ms	remaining: 324ms
109:	learn: 0.2866631	total: 391ms	remaining: 320ms
110:	learn: 0.2861470	total: 395ms	remaining: 317ms
111:	learn: 0.2852859	total: 399ms	remaining: 314ms
112:	learn: 0.2848884	total: 404ms	remaining: 311ms
113:	learn: 0.2846689	total: 409ms	remaining: 308ms
114:	learn: 0.2844608	total: 412ms	remaining: 305ms
115:	learn: 0.2836843	total: 416ms	remaining: 302ms
116:	learn: 0.2827350	total: 421ms	remaining: 298ms
117:	learn: 0.2823214	total: 425ms	remaining: 295ms
118:	learn: 0.2822881	total: 426ms	remaining: 290ms
119:	learn: 0.2820169	total: 430ms	remaining: 287ms
120:	learn: 0.2816482	total: 434ms	remaining: 283ms
121:	learn: 0.2808333	total: 438ms	remaining: 280ms
122:	learn: 0.2801747	total: 441ms	remaining: 276ms
123:	learn: 0.2801500	total: 443ms	remaining: 271ms
124:	learn: 0.2801131	total: 447ms	remaining: 268ms
125:	learn: 0.2798076	total: 450ms	remaining: 264ms
126:	learn: 0.2790933	total: 454ms	remaining: 261ms
127:	learn: 0.2783122	total: 458ms	remaining: 258ms
128:	learn: 0.2782937	total: 459ms	remaining: 253ms
129:	learn: 0.2778081	total: 463ms	remaining: 249ms
130:	learn: 0.2768026	total: 467ms	remaining: 246ms
131:	learn: 0.2764933	total: 470ms	remaining: 242ms
132:	learn: 0.2762652	total: 472ms	remaining: 238ms
133:	learn: 0.2756506	total: 477ms	remaining: 235ms
134:	learn: 0.2753081	total: 479ms	remaining: 231ms
135:	learn: 0.2751426	total: 483ms	remaining: 227ms
136:	learn: 0.2748865	total: 486ms	remaining: 224ms
137:	learn: 0.2748757	total: 488ms	remaining: 219ms
138:	learn: 0.2748566	total: 494ms	remaining: 217ms
139:	learn: 0.2747415	total: 496ms	remaining: 213ms
140:	learn: 0.2745483	total: 499ms	remaining: 209ms
141:	learn: 0.2736413	total: 503ms	remaining: 205ms
142:	learn: 0.2730806	total: 508ms	remaining: 202ms
143:	learn: 0.2730729	total: 510ms	remaining: 198ms
144:	learn: 0.2729607	total: 513ms	remaining: 194ms
145:	learn: 0.2725140	total: 516ms	remaining: 191ms
146:	learn: 0.2724210	total: 518ms	remaining: 187ms
147:	learn: 0.2721247	total: 521ms	remaining: 183ms
148:	learn: 0.2719112	total: 526ms	remaining: 180ms
149:	learn: 0.2714964	total: 530ms	remaining: 177ms
150:	learn: 0.2710067	total: 534ms	remaining: 173ms
151:	learn: 0.2709116	total: 538ms	remaining: 170ms
152:	learn: 0.2708042	total: 542ms	remaining: 167ms
153:	learn: 0.2706164	total: 546ms	remaining: 163ms
154:	learn: 0.2699036	total: 552ms	remaining: 160ms
155:	learn: 0.2695515	total: 554ms	remaining: 156ms
156:	learn: 0.2692895	total: 557ms	remaining: 152ms
157:	learn: 0.2689822	total: 559ms	remaining: 149ms
158:	learn: 0.2688360	total: 565ms	remaining: 146ms
159:	learn: 0.2684955	total: 568ms	remaining: 142ms
160:	learn: 0.2678256	total: 571ms	remaining: 138ms
161:	learn: 0.2677676	total: 575ms	remaining: 135ms
162:	learn: 0.2677189	total: 577ms	remaining: 131ms
163:	learn: 0.2673894	total: 580ms	remaining: 127ms
164:	learn: 0.2673008	total: 583ms	remaining: 124ms
165:	learn: 0.2669860	total: 586ms	remaining: 120ms
166:	learn: 0.2663631	total: 590ms	remaining: 117ms
167:	learn: 0.2656644	total: 594ms	remaining: 113ms
168:	learn: 0.2656197	total: 596ms	remaining: 109ms
169:	learn: 0.2653563	total: 598ms	remaining: 106ms
170:	learn: 0.2651169	total: 602ms	remaining: 102ms
171:	learn: 0.2650724	total: 605ms	remaining: 98.5ms
172:	learn: 0.2646183	total: 610ms	remaining: 95.1ms
173:	learn: 0.2646171	total: 611ms	remaining: 91.3ms
174:	learn: 0.2641417	total: 615ms	remaining: 87.9ms
175:	learn: 0.2638636	total: 620ms	remaining: 84.6ms
176:	learn: 0.2632777	total: 625ms	remaining: 81.2ms
177:	learn: 0.2631260	total: 629ms	remaining: 77.8ms
178:	learn: 0.2630397	total: 633ms	remaining: 74.2ms
179:	learn: 0.2629639	total: 636ms	remaining: 70.7ms
180:	learn: 0.2629631	total: 637ms	remaining: 66.9ms
181:	learn: 0.2623707	total: 642ms	remaining: 63.5ms
182:	learn: 0.2617349	total: 647ms	remaining: 60.1ms
183:	learn: 0.2616195	total: 649ms	remaining: 56.4ms
184:	learn: 0.2615749	total: 653ms	remaining: 52.9ms
185:	learn: 0.2614889	total: 656ms	remaining: 49.4ms
186:	learn: 0.2611967	total: 660ms	remaining: 45.9ms
187:	learn: 0.2610816	total: 663ms	remaining: 42.3ms
188:	learn: 0.2605525	total: 667ms	remaining: 38.8ms
189:	learn: 0.2604734	total: 672ms	remaining: 35.4ms
190:	learn: 0.2603678	total: 676ms	remaining: 31.8ms
191:	learn: 0.2602676	total: 679ms	remaining: 28.3ms
192:	learn: 0.2602668	total: 684ms	remaining: 24.8ms
193:	learn: 0.2597680	total: 688ms	remaining: 21.3ms
194:	learn: 0.2596563	total: 693ms	remaining: 17.8ms
195:	learn: 0.2592129	total: 697ms	remaining: 14.2ms
196:	learn: 0.2591257	total: 702ms	remaining: 10.7ms
197:	learn: 0.2591114	total: 707ms	remaining: 7.14ms
198:	learn: 0.2590467	total: 709ms	remaining: 3.56ms
199:	learn: 0.2587954	total: 712ms	remaining: 0us
0:	learn: 0.6753973	total: 5.76ms	remaining: 1.15s
1:	learn: 0.6591105	total: 10.6ms	remaining: 1.05s
2:	learn: 0.6437668	total: 13.5ms	remaining: 890ms
3:	learn: 0.6285783	total: 18.8ms	remaining: 921ms
4:	learn: 0.6148846	total: 20ms	remaining: 779ms
5:	learn: 0.6019651	total: 22.7ms	remaining: 734ms
6:	learn: 0.5898006	total: 27.4ms	remaining: 755ms
7:	learn: 0.5782805	total: 31.9ms	remaining: 765ms
8:	learn: 0.5664367	total: 36.4ms	remaining: 772ms
9:	learn: 0.5560576	total: 39.9ms	remaining: 758ms
10:	learn: 0.5454006	total: 44ms	remaining: 757ms
11:	learn: 0.5360306	total: 46.5ms	remaining: 728ms
12:	learn: 0.5271744	total: 48.3ms	remaining: 694ms
13:	learn: 0.5179875	total: 53.1ms	remaining: 706ms
14:	learn: 0.5096151	total: 56ms	remaining: 690ms
15:	learn: 0.5011865	total: 59.4ms	remaining: 683ms
16:	learn: 0.4932705	total: 61.9ms	remaining: 666ms
17:	learn: 0.4863222	total: 64.2ms	remaining: 649ms
18:	learn: 0.4798217	total: 66ms	remaining: 628ms
19:	learn: 0.4736718	total: 70.1ms	remaining: 630ms
20:	learn: 0.4676801	total: 73ms	remaining: 622ms
21:	learn: 0.4611810	total: 76.5ms	remaining: 619ms
22:	learn: 0.4542343	total: 79.6ms	remaining: 613ms
23:	learn: 0.4487802	total: 82.4ms	remaining: 604ms
24:	learn: 0.4439662	total: 84.8ms	remaining: 594ms
25:	learn: 0.4387463	total: 89.3ms	remaining: 597ms
26:	learn: 0.4329327	total: 92.5ms	remaining: 592ms
27:	learn: 0.4286787	total: 95.5ms	remaining: 587ms
28:	learn: 0.4234404	total: 98.7ms	remaining: 582ms
29:	learn: 0.4181371	total: 103ms	remaining: 584ms
30:	learn: 0.4145637	total: 106ms	remaining: 579ms
31:	learn: 0.4111601	total: 107ms	remaining: 564ms
32:	learn: 0.4076473	total: 110ms	remaining: 559ms
33:	learn: 0.4034907	total: 114ms	remaining: 554ms
34:	learn: 0.3983151	total: 118ms	remaining: 555ms
35:	learn: 0.3944120	total: 121ms	remaining: 550ms
36:	learn: 0.3908351	total: 123ms	remaining: 543ms
37:	learn: 0.3867940	total: 126ms	remaining: 537ms
38:	learn: 0.3838057	total: 128ms	remaining: 529ms
39:	learn: 0.3808566	total: 133ms	remaining: 534ms
40:	learn: 0.3786776	total: 135ms	remaining: 523ms
41:	learn: 0.3760681	total: 138ms	remaining: 520ms
42:	learn: 0.3713121	total: 142ms	remaining: 517ms
43:	learn: 0.3669959	total: 146ms	remaining: 517ms
44:	learn: 0.3647189	total: 150ms	remaining: 516ms
45:	learn: 0.3630239	total: 154ms	remaining: 515ms
46:	learn: 0.3614086	total: 155ms	remaining: 505ms
47:	learn: 0.3573839	total: 161ms	remaining: 509ms
48:	learn: 0.3541078	total: 165ms	remaining: 508ms
49:	learn: 0.3508540	total: 168ms	remaining: 505ms
50:	learn: 0.3489503	total: 171ms	remaining: 500ms
51:	learn: 0.3476026	total: 174ms	remaining: 495ms
52:	learn: 0.3464076	total: 175ms	remaining: 486ms
53:	learn: 0.3441518	total: 179ms	remaining: 485ms
54:	learn: 0.3410376	total: 182ms	remaining: 481ms
55:	learn: 0.3389356	total: 187ms	remaining: 480ms
56:	learn: 0.3356648	total: 191ms	remaining: 479ms
57:	learn: 0.3329182	total: 196ms	remaining: 479ms
58:	learn: 0.3314436	total: 199ms	remaining: 476ms
59:	learn: 0.3295765	total: 204ms	remaining: 476ms
60:	learn: 0.3266773	total: 208ms	remaining: 474ms
61:	learn: 0.3254868	total: 211ms	remaining: 470ms
62:	learn: 0.3231191	total: 214ms	remaining: 466ms
63:	learn: 0.3223725	total: 219ms	remaining: 466ms
64:	learn: 0.3208205	total: 223ms	remaining: 463ms
65:	learn: 0.3177610	total: 228ms	remaining: 462ms
66:	learn: 0.3162605	total: 233ms	remaining: 463ms
67:	learn: 0.3151543	total: 237ms	remaining: 460ms
68:	learn: 0.3124836	total: 240ms	remaining: 456ms
69:	learn: 0.3097436	total: 246ms	remaining: 456ms
70:	learn: 0.3070602	total: 250ms	remaining: 455ms
71:	learn: 0.3066117	total: 252ms	remaining: 448ms
72:	learn: 0.3043970	total: 256ms	remaining: 446ms
73:	learn: 0.3022155	total: 261ms	remaining: 444ms
74:	learn: 0.3018333	total: 263ms	remaining: 438ms
75:	learn: 0.3002282	total: 266ms	remaining: 434ms
76:	learn: 0.2982668	total: 270ms	remaining: 431ms
77:	learn: 0.2964109	total: 274ms	remaining: 429ms
78:	learn: 0.2957362	total: 277ms	remaining: 424ms
79:	learn: 0.2946682	total: 280ms	remaining: 421ms
80:	learn: 0.2924587	total: 285ms	remaining: 418ms
81:	learn: 0.2901453	total: 289ms	remaining: 416ms
82:	learn: 0.2894426	total: 293ms	remaining: 413ms
83:	learn: 0.2871727	total: 298ms	remaining: 411ms
84:	learn: 0.2853174	total: 302ms	remaining: 408ms
85:	learn: 0.2844220	total: 306ms	remaining: 406ms
86:	learn: 0.2837388	total: 309ms	remaining: 402ms
87:	learn: 0.2819646	total: 313ms	remaining: 398ms
88:	learn: 0.2812213	total: 315ms	remaining: 393ms
89:	learn: 0.2810523	total: 317ms	remaining: 388ms
90:	learn: 0.2806060	total: 320ms	remaining: 383ms
91:	learn: 0.2789421	total: 325ms	remaining: 381ms
92:	learn: 0.2781627	total: 329ms	remaining: 378ms
93:	learn: 0.2776508	total: 332ms	remaining: 375ms
94:	learn: 0.2774625	total: 335ms	remaining: 370ms
95:	learn: 0.2756511	total: 339ms	remaining: 367ms
96:	learn: 0.2749834	total: 343ms	remaining: 364ms
97:	learn: 0.2737589	total: 347ms	remaining: 361ms
98:	learn: 0.2726207	total: 349ms	remaining: 356ms
99:	learn: 0.2721730	total: 352ms	remaining: 352ms
100:	learn: 0.2710195	total: 357ms	remaining: 349ms
101:	learn: 0.2704131	total: 361ms	remaining: 347ms
102:	learn: 0.2693617	total: 366ms	remaining: 345ms
103:	learn: 0.2682798	total: 369ms	remaining: 341ms
104:	learn: 0.2675323	total: 372ms	remaining: 337ms
105:	learn: 0.2671059	total: 375ms	remaining: 333ms
106:	learn: 0.2665097	total: 379ms	remaining: 329ms
107:	learn: 0.2653989	total: 384ms	remaining: 327ms
108:	learn: 0.2645713	total: 387ms	remaining: 323ms
109:	learn: 0.2633811	total: 392ms	remaining: 320ms
110:	learn: 0.2629152	total: 394ms	remaining: 316ms
111:	learn: 0.2609426	total: 399ms	remaining: 314ms
112:	learn: 0.2602575	total: 404ms	remaining: 311ms
113:	learn: 0.2598500	total: 407ms	remaining: 307ms
114:	learn: 0.2595010	total: 411ms	remaining: 304ms
115:	learn: 0.2585533	total: 416ms	remaining: 301ms
116:	learn: 0.2574220	total: 419ms	remaining: 297ms
117:	learn: 0.2571509	total: 423ms	remaining: 294ms
118:	learn: 0.2566556	total: 428ms	remaining: 291ms
119:	learn: 0.2557563	total: 432ms	remaining: 288ms
120:	learn: 0.2553887	total: 436ms	remaining: 285ms
121:	learn: 0.2540570	total: 439ms	remaining: 281ms
122:	learn: 0.2537119	total: 442ms	remaining: 277ms
123:	learn: 0.2532708	total: 446ms	remaining: 273ms
124:	learn: 0.2516377	total: 449ms	remaining: 269ms
125:	learn: 0.2506636	total: 453ms	remaining: 266ms
126:	learn: 0.2497294	total: 457ms	remaining: 263ms
127:	learn: 0.2493426	total: 461ms	remaining: 259ms
128:	learn: 0.2491529	total: 464ms	remaining: 255ms
129:	learn: 0.2483968	total: 468ms	remaining: 252ms
130:	learn: 0.2480137	total: 471ms	remaining: 248ms
131:	learn: 0.2472558	total: 474ms	remaining: 244ms
132:	learn: 0.2472417	total: 476ms	remaining: 240ms
133:	learn: 0.2470825	total: 480ms	remaining: 237ms
134:	learn: 0.2465066	total: 483ms	remaining: 233ms
135:	learn: 0.2453623	total: 488ms	remaining: 230ms
136:	learn: 0.2451574	total: 491ms	remaining: 226ms
137:	learn: 0.2449708	total: 495ms	remaining: 222ms
138:	learn: 0.2447327	total: 498ms	remaining: 219ms
139:	learn: 0.2444020	total: 500ms	remaining: 214ms
140:	learn: 0.2441103	total: 504ms	remaining: 211ms
141:	learn: 0.2438665	total: 508ms	remaining: 208ms
142:	learn: 0.2428944	total: 513ms	remaining: 204ms
143:	learn: 0.2428655	total: 515ms	remaining: 200ms
144:	learn: 0.2424758	total: 518ms	remaining: 197ms
145:	learn: 0.2415271	total: 523ms	remaining: 193ms
146:	learn: 0.2408745	total: 526ms	remaining: 189ms
147:	learn: 0.2399991	total: 531ms	remaining: 186ms
148:	learn: 0.2396411	total: 535ms	remaining: 183ms
149:	learn: 0.2387801	total: 539ms	remaining: 180ms
150:	learn: 0.2381362	total: 544ms	remaining: 176ms
151:	learn: 0.2380463	total: 548ms	remaining: 173ms
152:	learn: 0.2373710	total: 554ms	remaining: 170ms
153:	learn: 0.2370978	total: 556ms	remaining: 166ms
154:	learn: 0.2363826	total: 560ms	remaining: 163ms
155:	learn: 0.2361451	total: 565ms	remaining: 159ms
156:	learn: 0.2360717	total: 569ms	remaining: 156ms
157:	learn: 0.2355062	total: 574ms	remaining: 153ms
158:	learn: 0.2349137	total: 579ms	remaining: 149ms
159:	learn: 0.2346585	total: 583ms	remaining: 146ms
160:	learn: 0.2346558	total: 584ms	remaining: 142ms
161:	learn: 0.2340144	total: 590ms	remaining: 138ms
162:	learn: 0.2339066	total: 592ms	remaining: 134ms
163:	learn: 0.2337879	total: 596ms	remaining: 131ms
164:	learn: 0.2332832	total: 599ms	remaining: 127ms
165:	learn: 0.2328151	total: 605ms	remaining: 124ms
166:	learn: 0.2327252	total: 609ms	remaining: 120ms
167:	learn: 0.2321216	total: 613ms	remaining: 117ms
168:	learn: 0.2319032	total: 617ms	remaining: 113ms
169:	learn: 0.2313854	total: 620ms	remaining: 109ms
170:	learn: 0.2311551	total: 624ms	remaining: 106ms
171:	learn: 0.2311092	total: 628ms	remaining: 102ms
172:	learn: 0.2311080	total: 630ms	remaining: 98.2ms
173:	learn: 0.2305932	total: 633ms	remaining: 94.6ms
174:	learn: 0.2303826	total: 637ms	remaining: 90.9ms
175:	learn: 0.2302480	total: 641ms	remaining: 87.4ms
176:	learn: 0.2297219	total: 646ms	remaining: 83.9ms
177:	learn: 0.2290707	total: 650ms	remaining: 80.3ms
178:	learn: 0.2290698	total: 651ms	remaining: 76.4ms
179:	learn: 0.2288986	total: 654ms	remaining: 72.7ms
180:	learn: 0.2287732	total: 657ms	remaining: 69ms
181:	learn: 0.2287722	total: 661ms	remaining: 65.4ms
182:	learn: 0.2287007	total: 665ms	remaining: 61.8ms
183:	learn: 0.2283546	total: 669ms	remaining: 58.2ms
184:	learn: 0.2282763	total: 671ms	remaining: 54.4ms
185:	learn: 0.2275250	total: 675ms	remaining: 50.8ms
186:	learn: 0.2270989	total: 678ms	remaining: 47.1ms

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bagging_temperature,param_depth,param_l2_leaf_reg,param_leaf_estimation_iterations,param_random_strength,params,...,split2_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,mean_train_score,std_train_score,rank_train_score
13,1.085619,0.015045,0.007182,0.000118,0.178914,3,3.381304,3,18.341148,"{'bagging_temperature': 0.17891372112276038, '...",...,0.799451,0.740824,0.104159,1,0.800328,0.874610,0.820977,0.831972,0.031306,23
4,1.125236,0.012505,0.007485,0.000281,0.528878,3,9.321459,4,19.240633,"{'bagging_temperature': 0.5288777012609818, 'd...",...,0.798788,0.736715,0.103583,2,0.802229,0.877894,0.817718,0.832614,0.032636,21
20,0.776718,0.015088,0.006970,0.000695,0.01,3,10.0,1,20.0,"{'bagging_temperature': 0.01, 'depth': 3, 'l2_...",...,0.797595,0.734008,0.089504,3,0.793763,0.871889,0.817467,0.827706,0.032706,27
22,0.778668,0.015083,0.006988,0.000405,0.95,3,10.0,1,20.0,"{'bagging_temperature': 0.95, 'depth': 3, 'l2_...",...,0.797595,0.734008,0.089504,3,0.793763,0.871889,0.817467,0.827706,0.032706,27
27,0.782524,0.014842,0.008551,0.001780,0.01,3,10.0,1,20.0,"{'bagging_temperature': 0.01, 'depth': 3, 'l2_...",...,0.797595,0.734008,0.089504,3,0.793763,0.871889,0.817467,0.827706,0.032706,27
28,0.767649,0.011665,0.008570,0.002220,0.95,3,10.0,1,20.0,"{'bagging_temperature': 0.95, 'depth': 3, 'l2_...",...,0.797595,0.734008,0.089504,3,0.793763,0.871889,0.817467,0.827706,0.032706,27
16,1.548904,0.054029,0.006761,0.000304,0.37729,3,1.0,10,9.551232,"{'bagging_temperature': 0.3772899390185143, 'd...",...,0.812276,0.728292,0.128598,7,0.809813,0.894842,0.832897,0.845851,0.035901,16
24,1.191354,0.004361,0.006926,0.000181,0.04885,3,5.193025,5,20.0,"{'bagging_temperature': 0.048849756429879126, ...",...,0.806826,0.727888,0.125223,8,0.794475,0.876129,0.824549,0.831717,0.033718,24
11,1.949316,0.136924,0.010016,0.000449,0.95,10,10.0,1,20.0,"{'bagging_temperature': 0.95, 'depth': 10, 'l2...",...,0.818708,0.727046,0.127731,9,0.810778,0.899719,0.834965,0.848487,0.037548,13
14,0.968498,0.010913,0.007503,0.000306,0.949755,4,1.0,1,20.0,"{'bagging_temperature': 0.9497551967583575, 'd...",...,0.802890,0.725718,0.127777,10,0.799626,0.883965,0.823386,0.835659,0.035508,20
18,0.780287,0.021294,0.007978,0.000967,0.167019,3,6.403524,1,18.533149,"{'bagging_temperature': 0.16701857017059923, '...",...,0.803523,0.722376,0.126308,11,0.793296,0.878099,0.820283,0.830559,0.035375,25
9,2.489138,0.096500,0.009345,0.001044,0.322138,7,2.235997,8,13.666809,"{'bagging_temperature': 0.32213819753490525, '...",...,0.807422,0.720997,0.138179,12,0.821424,0.907620,0.840378,0.856474,0.036984,12
15,0.772274,0.006325,0.006996,0.000449,0.901837,3,1.0,1,16.55458,"{'bagging_temperature': 0.9018371914037033, 'd...",...,0.797743,0.720844,0.117180,13,0.797877,0.883352,0.815408,0.832213,0.036862,22
0,1.711350,0.032809,0.007283,0.000171,0.45067,4,4.594705,9,14.34122,"{'bagging_temperature': 0.45066982785838816, '...",...,0.809281,0.715280,0.142247,14,0.808124,0.901244,0.830651,0.846673,0.039668,15
23,0.777643,0.022361,0.007487,0.000841,0.01,3,10.0,1,18.420209,"{'bagging_temperature': 0.01, 'depth': 3, 'l2_...",...,0.803111,0.714832,0.136154,15,0.793436,0.876533,0.820085,0.830018,0.034644,26
17,2.867566,0.109026,0.009770,0.000817,0.01,10,1.0,6,17.283373,"{'bagging_temperature': 0.01, 'depth': 10, 'l2...",...,0.818080,0.712094,0.157974,16,0.824072,0.908780,0.846061,0.859638,0.035890,10
29,1.505761,0.015091,0.006682,0.000359,0.406519,3,1.0,10,7.941715,"{'bagging_temperature': 0.4065187127443182, 'd...",...,0.794698,0.711469,0.135108,17,0.812265,0.897781,0.833171,0.847739,0.036400,14
12,3.719045,0.230591,0.010310,0.000239,0.896721,10,10.0,10,18.068525,"{'bagging_temperature': 0.8967207474288925, 'd...",...,0.822900,0.711274,0.164212,18,0.829313,0.912021,0.847601,0.862979,0.035473,7
26,1.297081,0.012827,0.007511,0.000563,0.471723,3,1.0,6,17.003205,"{'bagging_temperature': 0.47172315642837154, '...",...,0.808362,0.709929,0.143646,19,0.800967,0.892505,0.823631,0.839034,0.038925,19
7,2.424432,0.065134,0.008594,0.000285,0.588185,7,7.991447,6,9.376241,"{'bagging_temperature': 0.5881850321315569, 'd...",...,0.819420,0.709894,0.163636,20,0.827308,0.914600,0.846441,0.862783,0.037464,8
10,1.758728,0.026397,0.007705,0.000665,0.01,4,1.0,10,19.292225,"{'bagging_temperature': 0.01, 'depth': 4, 'l2_...",...,0.805353,0.708108,0.153984,21,0.808891,0.894441,0.826584,0.843305,0.036873,18
21,2.108583,0.037188,0.011292,0.003112,0.445401,10,1.0,1,9.76948,"{'bagging_temperature': 0.4454011483678925, 'd...",...,0.822055,0.706941,0.161090,22,0.826322,0.915488,0.851844,0.864552,0.037495,5
19,2.715429,0.075869,0.011493,0.002971,0.54026,10,1.0,4,20.0,"{'bagging_temperature': 0.540260252531708, 'de...",...,0.815145,0.706758,0.150781,23,0.828881,0.914434,0.846165,0.863160,0.036937,6
3,1.726017,0.014018,0.007512,0.000153,0.306004,4,6.49466,9,14.192879,"{'bagging_temperature': 0.30600383064671965, '...",...,0.801619,0.706291,0.134534,24,0.809821,0.892979,0.832233,0.845011,0.035131,17
2,2.162023,0.051405,0.008380,0.000548,0.153839,6,8.973622,7,10.892039,"{'bagging_temperature': 0.15383889220016234, '...",...,0.816812,0.703534,0.168382,25,0.825800,0.910933,0.843220,0.859984,0.036722,9
8,2.200783,0.061484,0.008468,0.000442,0.587811,7,4.655425,5,12.973916,"{'bagging_temperature': 0.5878112898295745, 'd...",...,0.814959,0.702550,0.173672,26,0.823831,0.911683,0.842129,0.859214,0.037846,11
6,3.049876,0.102941,0.009844,0.000426,0.738423,9,4.73498,2,6.128274,"{'bagging_temperature': 0.7384225143716443, 'd...",...,0.824054,0.698215,0.173822,27,0.842994,0.922434,0.856115,0.873848,0.034771,3
25,3.978723,0.194338,0.009975,0.000868,0.794838,10,1.0,10,11.045855,"{'bagging_temperature': 0.7948384646991397, 'd...",...,0.808961,0.691296,0.177899,28,0.837359,0.921224,0.854232,0.870938,0.036218,4
5,3.303530,0.037396,0.008065,0.000425,0.52109,7,4.225884,8,1.721193,"{'bagging_temperature': 0.5210901247602404, 'd...",...,0.793154,0.642971,0.181842,29,0.872986,0.935554,0.880687,0.896409,0.027858,1
1,3.431265,0.026766,0.007863,0.000353,0.906445,7,6.302278,9,1.65616,"{'bagging_temperature': 0.9064454397001084, 'd...",...,0.801799,0.635176,0.185014,30,0.870867,0.934159,0.881196,0.895407,0.027724,2

In [20]:
mt_catboost.train()

✅ Analysis report generated at outputs/model_analysis.html